//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Expression.Media.Effects;
using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace McuTools.Interfaces.Effects
{

    public class FoldTransitionEffectEffect : TransitionEffect 
    {
        public static readonly DependencyProperty Input2Property = ShaderEffect.RegisterPixelShaderSamplerProperty("Input2", typeof(FoldTransitionEffectEffect), 1);
        
        public FoldTransitionEffectEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("/MCUTools.Interfaces;component/Effects/FoldTransitionEffectEffect.ps", UriKind.Relative);
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
            this.UpdateShaderValue(Input2Property);
            this.UpdateShaderValue(ProgressProperty);
        }

        public Brush Input2
        {
            get
            {
                return ((Brush)(this.GetValue(Input2Property)));
            }
            set
            {
                this.SetValue(Input2Property, value);
            }
        }
        /// <summary>The Fold Amount, zero is no effect, 1 i full fold</summary>

        protected override TransitionEffect DeepCopy()
        {
            return new FoldTransitionEffectEffect();
        }
    }
}
