//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace McuTools.Interfaces.Effects {
	
	public class PngOverlayEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(PngOverlayEffect), 0);
		public static readonly DependencyProperty InColorProperty = DependencyProperty.Register("InColor", typeof(Color), typeof(PngOverlayEffect), new UIPropertyMetadata(Color.FromArgb(255, 0, 0, 0), PixelShaderConstantCallback(0)));
		public PngOverlayEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("/MCUTools.Interfaces;component/Effects/PngOverlayEffect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(InColorProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>Fill color</summary>
		public Color InColor {
			get {
				return ((Color)(this.GetValue(InColorProperty)));
			}
			set {
				this.SetValue(InColorProperty, value);
			}
		}
	}
}
